# Site settings
title: Matt Odille
description: Matt Odille is a pragmatic software engineer interested in using the right technologies to develop smart and well-written software that helps people.

# URL settings
url: "https://modille.github.io"
baseurl: "/resume"

# GitHub Pages settings
google_analytics: UA-93271269-1
show_downloads: false

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
gems:
  - github-pages
exclude:
  - Gemfile
  - Gemfile.lock
